# Generated by Django 5.0.6 on 2024-05-09 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('serial_num', models.IntegerField(default=0)),
                ('music', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MusicImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/')),
                ('merge_music', models.FileField(blank=True, null=True, upload_to='media/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
