# Generated by Django 5.0.6 on 2024-05-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='type',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Interval', 'Interval'), ('Chord_one', 'Chord_one'), ('Chord_two', 'Chord_two')], max_length=100, null=True),
        ),
    ]
